### ISSUE TITLE
Database error on enabling

### ISSUE THREAD

**Issue by clawoflight** [ChristophWurst/twofactor_admin#20] opened 2018-10-29 09:07 UTC
Hi, when I try to enable this app, I get the following error:
`SQLSTATE[42704]: Undefined object: 7 ERROR:  index "primary" does not exist`

My database back-end is postgres.

**Comment by ChristophWurst** [comment] 2018-10-30 06:45
Please tell me what server environment you're on, e.g. distribution, version, web server in use, php version, database in use and so on. Also, you didn't tell what version of the Nextcloud Server and which version of this app you're using.

**Comment by rowie** [comment] 2018-11-22 12:42
Same Error here:
An exception occurred while executing 'DROP INDEX "primary"': SQLSTATE[42704]: Undefined object: 7 ERROR: index "primary" does not exis

Cloud 14.0.3
Ubuntu Linux 18.04.1
Apache
PostgreSQL

VMware Appliance from:
 https://www.hanssonit.se/nextcloud-vm

i

**Comment by ChristophWurst** [comment] 2018-11-29 10:42
Error from @michag86 (#21)

```
$ sudo -u www-data php ./occ twofactorauth:admin:generate-code test

In AbstractMySQLDriver.php line 115:

  An exception occurred while executing 'INSERT INTO `oc_twofactor_admin_codes` (`user_id`, `code`, `expires`) VALUES(?, ?, ?)' with params ["test", "396811", 1541020156]:  
  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value                                                                                               
                                                                                                                                                                             
In PDOStatement.php line 107:
  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value  

In PDOStatement.php line 105:
  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value 
```

**Comment by ChristophWurst** [comment] 2018-11-29 10:47
Could you please check the table definition like

```
> describe oc_twofactor_admin_codes;
+---------+---------------------+------+-----+---------+-------+
| Field   | Type                | Null | Key | Default | Extra |
+---------+---------------------+------+-----+---------+-------+
| id      | bigint(20) unsigned | NO   | PRI | NULL    |       |
| user_id | varchar(64)         | NO   | PRI | NULL    |       |
| code    | varchar(6)          | NO   |     | NULL    |       |
| expires | bigint(20) unsigned | NO   |     | NULL    |       |
+---------+---------------------+------+-----+---------+-------+
4 rows in set (0.01 sec)
```

Do you have the same structure? If so, what about the indexes?

```
> show indexes from oc_twofactor_admin_codes;
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                    | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_twofactor_admin_codes |          0 | PRIMARY  |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| oc_twofactor_admin_codes |          0 | PRIMARY  |            2 | user_id     | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.00 sec)
```

**Comment by Miesepies** [comment] 2018-11-29 11:00
Also database error when enabling, however different from the above 2 (not sure if I had to create a new issue).

Nextcloud 14.0.4 docker image (official)
MariaDB docker image (official)

An exception occurred while executing 'ALTER TABLE oc_twofactor_admin_codes CHANGE `expires` expires BIGINT UNSIGNED DEFAULT NULL NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expires'

Could it be that "DEFAULT NULL NOT NULL" is the issue here?

```
MariaDB [nextcloud]> describe oc_twofactor_admin_codes;                                                                                                                           
+---------+---------------------+------+-----+---------+-------+                                                                                                                  
| Field   | Type                | Null | Key | Default | Extra |                                                                                                                  
+---------+---------------------+------+-----+---------+-------+                                                                                                                  
| id      | bigint(20) unsigned | NO   | PRI | NULL    |       |                                                                                                                  
| user_id | varchar(64)         | NO   | PRI | NULL    |       |                                                                                                                  
| code    | varchar(6)          | NO   |     | NULL    |       |                                                                                                                  
| expires | bigint(20) unsigned | YES  |     | NULL    |       |                                                                                                                  
+---------+---------------------+------+-----+---------+-------+                                                                                                                  
4 rows in set (0.002 sec)                                          

MariaDB [nextcloud]> show indexes from oc_twofactor_admin_codes;                                                                                                                  
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+     
| Table                    | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |     
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+     
| oc_twofactor_admin_codes |          0 | PRIMARY  |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |     
| oc_twofactor_admin_codes |          0 | PRIMARY  |            2 | user_id     | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |     
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+     
2 rows in set (0.000 sec)                     

```

```

**Comment by ChristophWurst** [comment] 2018-11-29 11:18
@nickvergessen any idea what might cause these weird database issues? Apparently either the primary key is missing then it's changed from single column to composite key at https://github.com/ChristophWurst/twofactor_admin/blob/master/lib/Migration/Version1Date20180907092152.php or it fails to autogenerate the value for the `id` column on insert. I cannot reproduce on any of my dev/prod instances.

**Comment by ChristophWurst** [comment] 2018-11-29 11:33
> I cannot reproduce on any of my dev/prod instances.

To be precise I tested with Mariadb 15.1 and sqlite.

**Comment by nickvergessen** [comment] 2018-11-29 12:40
Well it looks like you are migrating from "int default null" to "bigint not null" so the current entries need to be update to not have null anymore

**Comment by ChristophWurst** [comment] 2018-11-29 13:17
In https://github.com/ChristophWurst/twofactor_admin/blob/master/lib/Migration/Version1Date20180907092152.php? Well, that migration is from the same commit as the initial one, so they are both part of the initial release and therefore executed right away. I don't see any scenario where there could be data in the db, hence the migration should just work.

**Comment by ChristophWurst** [comment] 2018-11-29 13:20
I think you're referring to the error reported at https://github.com/ChristophWurst/twofactor_admin/issues/20#issuecomment-442793190. That is indeed the problem you described.

The other two errors look fishy though.

**Comment by MorrisJobke** [comment] 2018-12-03 09:57
I ran into this as well. The app was installed first in 15.0.0 RC 2.
```
mysql> describe oc_twofactor_admin_codes;
+---------+---------------------+------+-----+---------+-------+
| Field   | Type                | Null | Key | Default | Extra |
+---------+---------------------+------+-----+---------+-------+
| id      | bigint(20) unsigned | NO   | PRI | NULL    |       |
| user_id | varchar(64)         | NO   | PRI | NULL    |       |
| code    | varchar(6)          | NO   |     | NULL    |       |
| expires | bigint(20) unsigned | NO   |     | NULL    |       |
+---------+---------------------+------+-----+---------+-------+
4 rows in set (0.00 sec)

mysql> show indexes from oc_twofactor_admin_codes;
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                    | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_twofactor_admin_codes |          0 | PRIMARY  |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| oc_twofactor_admin_codes |          0 | PRIMARY  |            2 | user_id     | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+--------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.00 sec)

```

**Comment by ChristophWurst** [comment] 2018-12-03 13:20
I can reproduce :rocket: 

But only with https://hub.docker.com/_/mariadb/, my Arch linux mariadb runs smooth.

**Comment by ChristophWurst** [comment] 2018-12-03 14:13
This is the (correctly) derived diff from the migration. The sql, however, does not look right.

![bildschirmfoto von 2018-12-03 15-11-44](https://user-images.githubusercontent.com/1374172/49378811-daa9d980-f70d-11e8-90d7-8bb7c078a422.png)
![bildschirmfoto von 2018-12-03 15-12-13](https://user-images.githubusercontent.com/1374172/49378810-daa9d980-f70d-11e8-85c6-85c7d8a92e01.png)

```sql
ALTER TABLE oc_twofactor_admin_codes CHANGE `expires` expires BIGINT UNSIGNED DEFAULT NULL NOT NULL
```

**Comment by ChristophWurst** [comment] 2018-12-03 14:17
The correct SQL would be 

```sql
ALTER TABLE oc_twofactor_admin_codes CHANGE COLUMN `expires` expires BIGINT UNSIGNED NOT NULL
```

I suppose.

**Comment by ChristophWurst** [comment] 2018-12-03 15:10
Since I suspected an issue in the doctrine db abstraction logic (and therefore invalid sql), I experimentally updated the `doctrine/dbal` dependency to 2.8. This resolved the issue.

Could y'all check your mariadb version?

I've got

* `mysql  Ver 15.1 Distrib 10.1.37-MariaDB` (Arch) -> works fine
* `mysql  Ver 15.1 Distrib 10.1.37-MariaDB` (Debian) -> works fine
* `mysql  Ver 15.1 Distrib 10.3.11-MariaDB` (Docker) -> :boom: 

I conclude that mariadb 10.2 is the issue. Ref https://github.com/doctrine/dbal/pull/2825.

**Comment by ChristophWurst** [comment] 2018-12-03 18:48
Confirmed via CI:

10.1: :rocket: 
10.2: :boom: 

Ref https://github.com/ChristophWurst/twofactor_admin/pull/25/commits

**Comment by gpz1100** [comment] 2018-12-07 01:32
I'm seeing this issue too on a new install from this ova - https://www.hanssonit.se/nextcloud-vm/ .  Using ver 0.1.0 (nc 14.0.4)

That implementation of nextcloud is using psql.  The error is nearly identical.
---
An error occured during the request. Unable to proceed.
An exception occurred while executing ‘DROP INDEX “primary”’: SQLSTATE[42704]: Undefined object: 7 ERROR: index “primary” does not exist

**Comment by ChristophWurst** [comment] 2018-12-07 07:38
@gpz1100 thank you for the feedback. This is very unfortunate.

Could you please tell us which version of postgres that is? There might also be an incompatibility with the dbal lib.

**Comment by gpz1100** [comment] 2018-12-07 07:51
@christophWurst

psql (PostgreSQL) 10.6 (Ubuntu 10.6-0ubuntu0.18.04.1)

**Comment by ChristophWurst** [comment] 2018-12-11 08:52
While I unfortunately can not yet provide a solution for this database incompatibility for Nextcloud 15 yet, I have prepared releases of twofactor_totp and twofactor_u2f that now support being disabled via the CLI as well.

Please see https://github.com/nextcloud/twofactor_u2f/pull/311 and https://github.com/nextcloud/twofactor_totp/pull/360 and let me know if that helps you unlock your or your users accounts. Thank you :v:

**Comment by egena-its** [comment] 2018-12-18 01:54
Same event for me when installing app.  
"An exception occurred while executing 'DROP INDEX "primary"': SQLSTATE[42704]: Undefined object: 7 ERROR: index "primary" does not exist"
Thanks for looking into this. :)
Great work by the way.  Really good!

**Comment by mcwhelan** [comment] 2019-01-28 22:07
Same issue here:
Ubuntu 18.04.1
NC 15.02 
PostgreSQL 10.6
App version 0.2.0

Get the following error when I try and enable the app...

An exception occurred while executing 'DROP INDEX "primary"': SQLSTATE[42704]: Undefined object: 7 ERROR: index "primary" does not exist

Thx for all the hard work you guys do!

**Comment by tiagoefreitas** [comment] 2019-01-29 09:38
Same here, let me know if I can help debug it

**Comment by ChristophWurst** [comment] 2019-01-29 09:49
There's nothing to debug. Nextcloud 15 has some incompatibilities with newer DB versions. This should be fixed with Nextcloud 16 where we can finally update the `dbal` dependency (it requires php7.1 IIRC). @rullzer is already working on upgrading the library.

**Comment by ShapeShifter499** [comment] 2019-01-31 13:44
@ChristophWurst Just saw this today trying to enable 2FA on my Nextcloud for the first time.  I run Arch Linux and it looks like MariaDB got updated. ```mysql  Ver 15.1 Distrib 10.3.12-MariaDB, for Linux (x86_64) using readline 5.1``` 

I skimmed though reading. So this is a Nextcloud issue and not really your code?

**Comment by ShapeShifter499** [comment] 2019-01-31 13:47
@ChristophWurst Also one other question the main U2F/2FA apps  "twofactor_u2f" and "twofactor_totp
" are updated and supposed to be working for Nextcloud 15?

**Comment by ChristophWurst** [comment] 2019-01-31 14:09
TOTP and U2F are fine. This app will work for all DBs with Nextcloud 16: https://github.com/nextcloud/server/pull/13633

**Comment by rainbob** [comment] 2019-03-01 09:28
Hi, i had the same issue but by changing the table structure I was able to enable the app and it works perfectly !

Here's the code:

`DROP TABLE IF EXISTS twofactor_admin_codes;
CREATE TABLE twofactor_admin_codes (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  user_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  code varchar(6) COLLATE utf8mb4_bin NOT NULL,
  expires bigint(20) unsigned NOT NULL,
  PRIMARY KEY (id,user_id)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;`

**Comment by christianlupus** [comment] 2019-04-21 12:29
@ChristophWurst I was not diving deep into your code but may I just make a simple suggestion: Can you provide a reasonable default value in the SQL syntax? If the `expires` column is a timestamp or so you might give a (safe) default value. As you are setting the value on inserting into the table anyways, the default value is not much of relevance, am I right?
Just my 50ct, no offence.

**Comment by ChristophWurst** [comment] 2019-04-23 07:42
The SQL is generated by dbal, as stated above. A dbal update is required to fix this bug.

**Comment by christianlupus** [comment] 2019-04-23 09:30
This is right, it is mainly a bug in the dbal. In the [migration script](https://github.com/ChristophWurst/twofactor_admin/blob/master/lib/Migration/Version2Date20180926055748.php) however you only set the property to be not null. You do not set an explicit default value. The dbal backend does not know anything of your business logic so it cannot provide a useful default value in the SQL syntax anyways.

My suggestion was to set the default value in the named file to be zero (I thin it is a timestamp, thus 0 is in the past). This will case any code to be expired immediately (hence a safe default). However you set the expire date explicitly when inserting into the database. Then you override the default value and get a non-expired code.

**Comment by ChristophWurst** [comment] 2019-04-23 09:40
Good point. Now I get it, I think :) Could you open a PR for that?

**Comment by christianlupus** [comment] 2019-04-23 11:56
I opened a PR as requested. For me this single added line of code makes the app install under mariadb and NC 15.
The PR is against `master` but should be better taken against V0.2.0 as the current master branch only is compatible with NC V16. I did not know how to set up this PR correctly (see history in my forked repo).

**Comment by ChristophWurst** [comment] 2019-04-23 12:48
We can backport the fix once we know it works on master.

**Closed** 2019-04-24 11:51 UTC
Labels: 0. to triage, needs info

**Comment by christianlupus** [comment] 2019-04-24 13:30
> We can backport the fix once we know it works on master.

You will do this, I think, right?
